apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: aws-ebs-pvc-kong
   namespace: kong
   annotations:
      volume.beta.kubernetes.io/storage-class: aws-ebs
spec:
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 20Gi